# fly.toml app configuration file generated for sundry-migrations on 2024-12-05T09:17:49-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sundry-migrations'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

