# fly.toml app configuration file generated for sundry-api on 2024-12-12T21:37:27-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sundry-api'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  API_LOG="api=debug,tower_http=debug,axum::rejection=trace,sqlparser::error"
  API_PORT=8000

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
